modLoader = "javafml"
loaderVersion = "[0,)"
issueTrackerURL = "https://github.com/CodeF53/Obsfucator/issues"
license = "${license}"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${displayName}"
authors = "CodeF53#0241"
description = '''
Fixes ChatReporting by making everything you send and receive Obfuscated
'''
#logoFile = ""

[[dependencies.${id}]]
modId = "forge"
mandatory = true
versionRange = "[0.0.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "architectury"
mandatory = true
versionRange = "[0.0.0,)"
ordering = "AFTER"
side = "BOTH"